---
collections:
  - name: community.proxmox
    version: 1.4.0
  - name: ansible.windows
    version: 3.2.0
  - name: cisco.ios 
    version: 11.0.0
  - name: ansible.netcommon
    version: 8.1.0
  - name: netbox.netbox
    version: 3.21.0
  - name: community.general
    version: 12.0.0
  - name: ansible.utils
    version: 6.0.0
  - name: ansible.posix
    version: 2.1.0

